### ISSUE TITLE
Testing Github

### ISSUE THREAD

**Issue by mloulakis** [TeoSakel/NTUA_Stochastic_Processes#1]
Η τελευταία έκδοση του βιβλίου αναρτήθηκε στον Κάλλιπο την Παρασκευή το απόγευμα. Αυτήν θα κατεβάσουν οι φετινοί φοιτητές και ας αναφερόμαστε στην αρίθμηση που υπάρχει εκεί για όλες τις ασκήσεις. Το link είναι αυτό
https://repository.kallipos.gr/handle/11419/6003
Φέτος συνδιδάσκει το μάθημα ο Αριστείδης Δούμας, please note.

**Comment by TeoSakel** [comment]
Είμαστε 6 ώρες πίσω θαρρώ...

**Comment by mloulakis** [comment]
Very good!

Έκανα update to comment μου τώρα.

**Comment by TeoSakel** [comment]
Ok!
Τα διόρθωσα με αυτό το commit 53ed740f0bced6885ce63db136ebc1a5b131f8a1
