### ISSUE TITLE
Spelling error in Exercise 36?

### ISSUE THREAD

**Issue by TeoSakel** [TeoSakel/NTUA_Stochastic_Processes#2]
@mloulakis στην άσκηση 36 (Κεφάλαιο 2) ζητάτε να μοντελοποιήσουν την άσκηση 20 του βιβλίου.
Μήπως εννοείτε την 19 που μοιάζει πιο κοντική στα παραδείγματα?

**Comment by mloulakis** [comment]
Την 20 εννοώ, αλλά θέλουμε ο αλγόριθμος να υπολογίζει την κατανομή (όχι την πιθανότητα) της άσκησης 20. Ας δώσουμε κάποια αρχική κατανομή δεν έχει σημασία ποια. 

Θα πρέπει να πάρουν N δείγματα της αλυσίδας και να σημειώσουν που θα είναι έπειτα από n βήματα.
Θα χρειαστούν δηλαδή έναν counter για κάθε κατάσταση.
