### ISSUE TITLE
Πρόβλημα με δεύτερη προγραμματιστική άσκηση

### ISSUE THREAD

**Issue by vaggkall** [TeoSakel/NTUA_Stochastic_Processes#3]
Γεια σας,

 προσπαθώ να κάνω την δεύτερη προγραμματιστική άσκηση όμως για κάποιο λόγο έχω πρόβλημα με την κωδικοποίηση του κειμένου της άσκησης. Όταν πατάω πάνω στην εκφώνηση δεν μου κατεβάζει κάποιο αρχείο αλλα ανοίγει νέα καρτέλα. Έκανα copy-paste το κειμενο και προσάθησα να ανοίξω με το jupyter το αρχείο αλλά ενώ τον κώδικα της python τον εμφανίζει κανονικά το υπόλοιπο κείμενο το εμφανίζει με ιερογλυφικά. Μπορεί να βρεθεί κάποια λύση? Υπάρχει περίπτωση το πρόβλημα να είναι ότι έχω ubuntu? 
  Ευχαριστώ.

Με εκτίμηση,
 Βαγγέλης

**Comment by TeoSakel** [comment]
Μάλλον δεν το έσωσες σαν UTF-8 format. 
Δοκίμασε αντί να κάνεις copy-paste να κάνεις δεξί-κλίκ στο link και *save link as*.
Και εγώ Linux έχω και δεν μου εμφανίζεται αυτό το πρόβλημα.
Αν δεν πιάσει αυτό που σου είπα τότε μπορεί να είναι θέμα τον fonts που έχεις.
