### ISSUE TITLE
προβλημα εργαστηριακης ασκησης 2 

### ISSUE THREAD

**Issue by leloulv** [TeoSakel/NTUA_Stochastic_Processes#4]

**Comment by leloulv** [comment]
βγάζει  συνέχεια συντακτικό λάθος

**Comment by TeoSakel** [comment]
Μην ποστάρεις λύσεις των ασκήσεων στο φόρουμ!

Καλύτερα στείλε μου email με το πρόβλημα και γράψε μου και το error message που σου βγάζει.
Είδα αρκετά σημεία που μπορεί να έχει θέμα ο κώδικας.
Σαν συμβουλή απέφευγε τα one-liners

**Comment by leloulv** [comment]
συγνωμη, ποιο ειναι το email σας?

**Comment by TeoSakel** [comment]
stochproc.tech@gmail.com
