### ISSUE TITLE
Εργαστηριακη ασκηση 2 ( και γενικα) 

### ISSUE THREAD

**Issue by yugi45** [TeoSakel/NTUA_Stochastic_Processes#5]
μου βγαζει το παρακατω ερρορ
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-12-d5e2dea8efe1> in <module>()
     47     for i in range(N):
     48         mc.start()  # new experiment
---> 49         for j in range(steps):  mc.move()
     50         if mc.running_state == 'GA':  counter += 1
     51 

C:\Users\Spin\Desktop\Lab 1\simple_markov_chain_lib.py in move(self)
    127     def move(self):
    128         """Moves to the next state and updates all relevant fields"""
--> 129         transition_probs = self._states[self.running_state]
    130         self.running_state = self._next_state(transition_probs)
    131         self.steps += 1

KeyError: 0
το προβλημα αφορα τη συναρτηση mc.move για καποιο λογο και δεν μπορω να βρω το λαθος (δεν γνωριζω και python )

**Comment by TeoSakel** [comment]
Μάλλον δεν έχεις ορίσει σωστά τον πίνακα πιθανοτήτων μετάβασης.
ΣΙγουρέψου ότι έχεις συμπεριλάβει όλες τις πιθανές καταστάσεις
