### ISSUE TITLE
προβλημα με την φορτωση του αρχείου

### ISSUE THREAD

**Issue by yugi45** [TeoSakel/NTUA_Stochastic_Processes#6]
αντιμετωπίζω προβλημα με το να δω το αρχείο στο jupyter.
ξεκιναω με το να αντιγράψω των ανεβασμένο κώδικα στο σημειωματαριο και εν συνέχεια να αλλάξω την επέκταση σε .ipynb (οπως και την προηγούμενη φορα) , αλλα τώρα οταν ανοίγω απο τον notebook δεν μου ανοίγει το αρχείο αλλα μου βγάζει ασαφή errors..
![screenshot_1](https://cloud.githubusercontent.com/assets/17065362/24628538/610f0c0e-18bf-11e7-9e2b-a0c7f2637d66.png)

**Comment by TeoSakel** [comment]
Μάλλον έχει πρόβλημα το encoding. (Γράφει UnicodeDecodeError)

Καλύτερα είναι να μην κάνεις copy-paste το notebook αλλά **δεξί-κλίκ, save as**

**Comment by yugi45** [comment]
πραγματι δουλεψε, ευχαριστω πολυ !
